#include "ai\_compile.sqf";
#include "cache\_compile.sqf";
#include "common\_compile.sqf";
#include "core\_compile.sqf";
#include "init\_compile.sqf";
#include "intel\_compile.sqf";
#include "misc\_compile.sqf";
#include "mission\_compile.sqf";
#include "spawn\_compile.sqf";