factions = [
    //British Army
    [
        //Arsenal
        [
            //Common
            [
                //Helmets
                [
                ],
                //Uniforms
                [
                ],
                //Vests
                [
                ],
                //Weapons
                [
                ],
                //Misc
                [
                ]
            ],
            //Role specific
            [
                //Role 0
                [
                    //Helmets
                    [
                    ],
                    //Uniforms
                    [
                    ],
                    //Vests
                    [
                    ],
                    //Weapons
                    [
                    ],
                    //Misc
                    [
                    ]
                ],
                //Role 1
                [
                    //Helmets
                    [
                    ],
                    //Uniforms
                    [
                    ],
                    //Vests
                    [
                    ],
                    //Weapons
                    [
                    ],
                    //Misc
                    [
                    ]
                ]
            ]
        ],
        //Vehicles
        [
            //Cars
            [
            ],
            //APC
            [
            ],
            //IFV
            [
            ],
            //Tanks
            [
            ],
            //Helicopters
            [
            ],
            //Planes
            [
            ]
        ],
        //Flag classname
        ""
    ],
    //US Army
    [
        //Arsenal
        [
            //Common
            [
                //Helmets
                [
                ],
                //Uniforms
                [
                ],
                //Vests
                [
                ],
                //Weapons
                [
                ],
                //Misc
                [
                ]
            ],
            //Role specific
            [
                //Role 0
                [
                    //Helmets
                    [
                    ],
                    //Uniforms
                    [
                    ],
                    //Vests
                    [
                    ],
                    //Weapons
                    [
                    ],
                    //Misc
                    [
                    ]
                ],
                //Role 1
                [
                    //Helmets
                    [
                    ],
                    //Uniforms
                    [
                    ],
                    //Vests
                    [
                    ],
                    //Weapons
                    [
                    ],
                    //Misc
                    [
                    ]
                ]
            ]
        ],
        //Vehicles
        [
            //Cars
            [
                //Format = [classname, displayname, points, initscript]
                ["classname1", "car1", 0, {}],
                ["classname2", "car2", 0, {}]
            ],
            //APC
            [
            ],
            //IFV
            [
            ],
            //Tanks
            [
            ],
            //Helicopters
            [
            ],
            //Planes
            [
            ]
        ],
        //Flag classname
        ""
    ],
    //US Marine Corps
    [
        //Arsenal
        [
            //Common
            [
                //Helmets
                [
                ],
                //Uniforms
                [
                ],
                //Vests
                [
                ],
                //Weapons
                [
                ],
                //Misc
                [
                ]
            ],
            //Role specific
            [
                //Role 0
                [
                    //Helmets
                    [
                    ],
                    //Uniforms
                    [
                    ],
                    //Vests
                    [
                    ],
                    //Weapons
                    [
                    ],
                    //Misc
                    [
                    ]
                ],
                //Role 1
                [
                    //Helmets
                    [
                    ],
                    //Uniforms
                    [
                    ],
                    //Vests
                    [
                    ],
                    //Weapons
                    [
                    ],
                    //Misc
                    [
                    ]
                ]
            ]
        ],
        //Vehicles
        [
            //Cars
            [
            ],
            //APC
            [
            ],
            //IFV
            [
            ],
            //Tanks
            [
            ],
            //Helicopters
            [
            ],
            //Planes
            [
            ]
        ],
        //Flag classname
        ""
    ]
];