factions = [
    //British Army
    [
        //Arsenal
        [
            //Helmets
            [
            ],
            //Uniforms
            [
            ],
            //Vests
            [
            ],
            //Weapons
            [
            ],
            //Misc
            [
            ]
        ],
        //Vehicles
        [
            //Cars
            [
            ],
            //APC
            [
            ],
            //IFV
            [
            ],
            //Tanks
            [
            ],
            //Helicopters
            [
            ],
            //Planes
            [
            ]
        ],
        //Flag classname
        ""
    ],
    //US Army
    [
        //Arsenal
        [
            //Helmets
            [
                "rhsusf_ach_helmet_ocp",
                "rhsusf_ach_helmet_ess_ocp",
                "rhsusf_ach_helmet_headset_ocp",
                "rhsusf_ach_helmet_headset_ess_ocp"
            ],
            //Uniforms
            [
                "",
                "",
            ],
            //Vests
            [
                "",
                "",
            ],
            //Weapons
            [
                "",
                ""
            ],
            //Misc
            [
                "",
                ""
            ]
        ],
        //Vehicles
        [
            //Cars
            [
            ],
            //APC
            [
            ],
            //IFV
            [
            ],
            //Tanks
            [
            ],
            //Helicopters
            [
            ],
            //Planes
            [
            ]
        ],
        //Flag classname
        ""
    ],
    //US Marine Corps
    [
        //Arsenal
        [
            //Helmets
            [
            ],
            //Uniforms
            [
            ],
            //Vests
            [
            ],
            //Weapons
            [
            ],
            //Misc
            [
            ]
        ],
        //Vehicles
        [
            //Cars
            [
            ],
            //APC
            [
            ],
            //IFV
            [
            ],
            //Tanks
            [
            ],
            //Helicopters
            [
            ],
            //Planes
            [
            ]
        ],
        //Flag classname
        ""
    ]
];